"use client";

import { useMemo, useRef, useState } from "react";
import { createCrmId, crmContactStageLabel, crmContactStages, crmDashboard, crmDaysUntil, crmOpportunityStageLabel, crmOpportunityStages, crmWorkspace, normalizeCrmContact, normalizeCrmStore, previewCrmCsv, receivedReferralCandidates, updateCrmWorkspace, type CrmActivityType, type CrmContact, type CrmContactStage, type CrmCsvPreviewRow, type CrmOpportunity, type CrmOpportunityStage, type CrmTask, type CrmWorkspace } from "@/lib/crm";
import { loadTool, saveTool, TOOL_KEYS } from "@/lib/tool-storage";
import type { Business, Member, Referral } from "@/lib/types";

type View = "today" | "contacts" | "pipeline";
type ContactDraft = { name: string; company: string; email: string; phone: string; metAt: string };
const emptyContact: ContactDraft = { name: "", company: "", email: "", phone: "", metAt: "" };
const activityMeta: Record<CrmActivityType, string> = { note: "📝 Note", call: "📞 Call", email: "✉️ Email", meeting: "🤝 Meeting", referral: "🔁 Referral" };

export function BusinessCrmTool({ businessId, members = [], businessById = new Map(), referrals = [], currentMemberId = "", initialWorkspace, onPersist }: { businessId: string; members?: Member[]; businessById?: Map<string, Business>; referrals?: Referral[]; currentMemberId?: string; initialWorkspace?: CrmWorkspace; onPersist?: (workspace: CrmWorkspace) => Promise<void> }) {
  const first = useRef(initialWorkspace ?? crmWorkspace(normalizeCrmStore(loadTool<unknown>(TOOL_KEYS.crm, null), businessId), businessId));
  const [workspace, setWorkspace] = useState(first.current); const latest = useRef(workspace); const queue = useRef(Promise.resolve());
  const [saveState, setSaveState] = useState<"saved" | "saving" | "error">("saved");
  const [view, setView] = useState<View>("today"); const [selectedContactId, setSelectedContactId] = useState<string | null>(null); const [selectedOpportunityId, setSelectedOpportunityId] = useState<string | null>(null);
  const [search, setSearch] = useState(""); const [filter, setFilter] = useState<"all" | CrmContactStage>("all"); const [form, setForm] = useState<"contact" | "task" | "opportunity" | null>(null);
  const [contactDraft, setContactDraft] = useState<ContactDraft>(emptyContact); const [taskDraft, setTaskDraft] = useState({ title: "", dueDate: "", contactId: "", opportunityId: "" }); const [opportunityDraft, setOpportunityDraft] = useState({ title: "", contactId: "", value: "", expectedClose: "" });
  const [activityDraft, setActivityDraft] = useState({ type: "note" as CrmActivityType, text: "", date: new Date().toISOString().slice(0, 10) }); const [csvPreview, setCsvPreview] = useState<CrmCsvPreviewRow[]>([]); const [message, setMessage] = useState("");
  const today = new Date().toISOString().slice(0, 10);

  function persist(next: CrmWorkspace) {
    latest.current = next; setWorkspace(next); setMessage("");
    if (!onPersist) { const store = normalizeCrmStore(loadTool<unknown>(TOOL_KEYS.crm, null), businessId); saveTool(TOOL_KEYS.crm, updateCrmWorkspace(store, next)); return; }
    setSaveState("saving"); queue.current = queue.current.then(() => onPersist(next)).then(() => { if (latest.current === next) setSaveState("saved"); }).catch(() => { setSaveState("error"); setMessage("Changes could not be saved. Reload before editing again so newer business data is not overwritten."); });
  }
  const fail = (text: string) => setMessage(text);
  const updateContact = (id: string, patch: Partial<CrmContact>) => persist({ ...workspace, contacts: workspace.contacts.map(c => c.id === id ? { ...c, ...patch } : c) });
  function addContact(raw: Partial<CrmContact>) { const contact = normalizeCrmContact(raw); persist({ ...workspace, contacts: [...workspace.contacts, contact] }); return contact; }
  function submitContact() { if (!contactDraft.name.trim()) return fail("Enter a contact name."); if (contactDraft.email && !/^\S+@\S+\.\S+$/.test(contactDraft.email)) return fail("Enter a valid email address."); addContact({ ...contactDraft, name: contactDraft.name.trim() }); setContactDraft(emptyContact); setForm(null); }
  function submitTask(defaultContactId = "") { if (!taskDraft.title.trim() || !taskDraft.dueDate) return fail("A task needs a title and due date."); persist({ ...workspace, tasks: [...workspace.tasks, { id: createCrmId("task"), title: taskDraft.title.trim(), dueDate: taskDraft.dueDate, contactId: taskDraft.contactId || defaultContactId || undefined, opportunityId: taskDraft.opportunityId || undefined, createdAt: Date.now() }] }); setTaskDraft({ title: "", dueDate: "", contactId: "", opportunityId: "" }); setForm(null); }
  const updateTask = (id: string, patch: Partial<CrmTask>) => persist({ ...workspace, tasks: workspace.tasks.map(t => t.id === id ? { ...t, ...patch } : t) });
  const deleteTask = (id: string) => persist({ ...workspace, tasks: workspace.tasks.filter(t => t.id !== id) });
  function submitOpportunity() { if (!opportunityDraft.title.trim() || !opportunityDraft.contactId) return fail("Choose a contact and enter an opportunity name."); const value = opportunityDraft.value ? Number(opportunityDraft.value) : null; if (value !== null && (!Number.isFinite(value) || value < 0)) return fail("Opportunity value must be zero or more."); const now = Date.now(); persist({ ...workspace, opportunities: [...workspace.opportunities, { id: createCrmId("opportunity"), contactId: opportunityDraft.contactId, title: opportunityDraft.title.trim(), stage: "new", value, expectedClose: opportunityDraft.expectedClose, source: "manual", note: "", stageHistory: [], createdAt: now, updatedAt: now }] }); setOpportunityDraft({ title: "", contactId: "", value: "", expectedClose: "" }); setForm(null); }
  function updateOpportunity(id: string, patch: Partial<CrmOpportunity>) { persist({ ...workspace, opportunities: workspace.opportunities.map(o => o.id !== id ? o : { ...o, ...patch, stageHistory: patch.stage && patch.stage !== o.stage ? [...o.stageHistory, { id: createCrmId("stage"), from: o.stage, to: patch.stage, changedAt: new Date().toISOString() }] : o.stageHistory, updatedAt: Date.now() }) }); }
  function deleteContact(id: string) { if (!window.confirm("Delete this contact and its tasks and opportunities?")) return; const opportunityIds = new Set(workspace.opportunities.filter(o => o.contactId === id).map(o => o.id)); persist({ ...workspace, contacts: workspace.contacts.filter(c => c.id !== id), opportunities: workspace.opportunities.filter(o => o.contactId !== id), tasks: workspace.tasks.filter(t => t.contactId !== id && !opportunityIds.has(t.opportunityId ?? "")) }); setSelectedContactId(null); }
  async function chooseCsv(file?: File) { if (!file) return; if (file.size > 2_000_000) return fail("Choose a CSV smaller than 2 MB."); const preview = previewCrmCsv(await file.text(), workspace.contacts); if (!preview.length) return fail("The CSV needs a header row and at least one contact."); setCsvPreview(preview); setMessage(""); }
  function importCsv() { const ready = csvPreview.filter(r => r.status === "ready"); if (!ready.length) return fail("There are no new valid contacts to import."); persist({ ...workspace, contacts: [...workspace.contacts, ...ready.map(r => normalizeCrmContact(r.contact))] }); setCsvPreview([]); }
  function exportCsv() { const rows = [["Name", "Company", "Title", "Email", "Phone", "Tags", "Met at", "Note"], ...workspace.contacts.map(c => [c.name, c.company, c.title, c.email, c.phone, c.tags.join("; "), c.metAt, c.note])]; const csv = rows.map(row => row.map(cell => `"${cell.replaceAll('"', '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const a = document.createElement("a"); a.href = url; a.download = "crm-contacts.csv"; a.click(); URL.revokeObjectURL(url); }
  function importMember(id: string) { const m = members.find(x => x.id === id); if (m) addContact({ name: m.name, title: m.title, email: m.email, phone: m.phone, company: businessById.get(m.businessId)?.name ?? "", metAt: "SBRA directory", stage: "connected" }); }
  function convertReferral(referral: Referral) { const introduced = referral.introducedMemberId ? members.find(m => m.id === referral.introducedMemberId) : undefined; const name = referral.kind === "lead" ? referral.prospectName || "Referral prospect" : introduced?.name || "Introduced member"; const detail = referral.kind === "lead" ? referral.prospectContact || "" : introduced?.email || ""; const existing = workspace.contacts.find(c => (detail.includes("@") && c.email.toLowerCase() === detail.toLowerCase()) || c.name.toLowerCase() === name.toLowerCase()); const contact = existing ?? normalizeCrmContact({ name, email: detail.includes("@") ? detail : "", phone: detail.includes("@") ? "" : detail, metAt: "SBRA referral", activities: [{ id: createCrmId("activity"), type: "referral", date: today, text: referral.need || "Referral received through SBRA" }] }); const now = Date.now(); const opportunityId = createCrmId("opportunity"); persist({ ...workspace, contacts: existing ? workspace.contacts : [...workspace.contacts, contact], opportunities: [...workspace.opportunities, { id: opportunityId, contactId: contact.id, title: referral.need || `Opportunity with ${name}`, stage: "new", value: null, expectedClose: "", source: "referral", referralId: referral.id, note: "", stageHistory: [], createdAt: now, updatedAt: now }], tasks: [...workspace.tasks, { id: createCrmId("task"), title: `Follow up with ${name}`, dueDate: today, contactId: contact.id, opportunityId, createdAt: now }] }); }

  const contactById = useMemo(() => new Map(workspace.contacts.map(c => [c.id, c])), [workspace.contacts]); const selected = selectedContactId ? contactById.get(selectedContactId) : undefined; const selectedOpportunity = selectedOpportunityId ? workspace.opportunities.find(o => o.id === selectedOpportunityId) : undefined; const stats = crmDashboard(workspace, today); const candidates = receivedReferralCandidates(referrals, currentMemberId, workspace); const openTasks = workspace.tasks.filter(t => !t.completedAt).sort((a, b) => a.dueDate.localeCompare(b.dueDate)); const taskProps = { contacts: contactById, opportunities: workspace.opportunities, today, onUpdate: updateTask, onDelete: deleteTask };
  if (selectedOpportunity) return <OpportunityDetail opportunity={selectedOpportunity} contacts={workspace.contacts} onBack={() => setSelectedOpportunityId(null)} onUpdate={patch => updateOpportunity(selectedOpportunity.id, patch)} />;
  if (selected) return <div className="tool-body"><button className="tool-back" onClick={() => setSelectedContactId(null)}>← All contacts</button><article className="glass-panel tool-panel"><div className="crm-detail-head"><button className={selected.priority ? "crm-star on" : "crm-star"} onClick={() => updateContact(selected.id, { priority: !selected.priority })}>★</button><div className="crm-detail-title"><input className="crm-name-input" value={selected.name} onChange={e => updateContact(selected.id, { name: e.target.value })} /><div className="crm-inline-fields"><input value={selected.title} onChange={e => updateContact(selected.id, { title: e.target.value })} placeholder="Title" /><input value={selected.company} onChange={e => updateContact(selected.id, { company: e.target.value })} placeholder="Company" /></div></div></div><div className="crm-stage-row">{crmContactStages.map(s => <button key={s.key} className={selected.stage === s.key ? `crm-stage-pick active stage-${s.key}` : "crm-stage-pick"} onClick={() => updateContact(selected.id, { stage: s.key })}>{s.label}</button>)}</div></article><ContactDetails contact={selected} update={patch => updateContact(selected.id, patch)} /><article className="glass-panel tool-panel"><SectionHead label="Follow-up tasks" title={`${workspace.tasks.filter(t => t.contactId === selected.id && !t.completedAt).length} open`} button="+ Task" action={() => { setTaskDraft({ title: `Follow up with ${selected.name}`, dueDate: today, contactId: selected.id, opportunityId: "" }); setForm("task"); }} />{form === "task" && <TaskForm draft={taskDraft} setDraft={setTaskDraft} contacts={workspace.contacts} opportunities={workspace.opportunities} submit={() => submitTask(selected.id)} />}<TaskList tasks={workspace.tasks.filter(t => t.contactId === selected.id)} {...taskProps} /></article><article className="glass-panel tool-panel"><p className="section-label">Opportunities</p>{workspace.opportunities.filter(o => o.contactId === selected.id && !o.archivedAt).map(o => <OpportunityRow key={o.id} opportunity={o} contact={selected} open={() => setSelectedOpportunityId(o.id)} onStage={stage => updateOpportunity(o.id, { stage })} />)}{!workspace.opportunities.some(o => o.contactId === selected.id && !o.archivedAt) && <p className="tool-hint">No opportunities for this contact yet.</p>}</article><Activity contact={selected} draft={activityDraft} setDraft={setActivityDraft} fail={fail} save={patch => updateContact(selected.id, patch)} /><button className="secondary-button crm-danger" onClick={() => deleteContact(selected.id)}>Delete contact</button></div>;
  return <div className="tool-body"><div className="crm-view-tabs">{(["today", "contacts", "pipeline"] as View[]).map(v => <button key={v} className={view === v ? "active" : ""} onClick={() => setView(v)}>{v === "today" ? "Today" : v[0].toUpperCase() + v.slice(1)}</button>)}<span className={`crm-save-state ${saveState}`}>{saveState === "saving" ? "Saving…" : saveState === "error" ? "Save failed" : onPersist ? "Saved" : "Saved on this device"}</span></div>{message && <p className="crm-message" role="alert">{message}</p>}<article className="glass-panel tool-panel"><div className="tool-metric-grid crm-stats"><Metric n={stats.contacts} label="Contacts" /><Metric n={stats.dueToday} label="Due today" /><Metric n={stats.overdue} label="Overdue" /><Metric n={stats.openOpportunities} label="Open opportunities" /><Metric n={stats.wonOpportunities} label="Won" /></div></article>
    {view === "today" && <><article className="glass-panel tool-panel"><SectionHead label="Today" title="Keep the business moving" button="+ Add task" action={() => { setTaskDraft({ title: "", dueDate: today, contactId: "", opportunityId: "" }); setForm("task"); }} />{form === "task" && <TaskForm draft={taskDraft} setDraft={setTaskDraft} contacts={workspace.contacts} opportunities={workspace.opportunities} submit={() => submitTask()} />}<TaskList tasks={openTasks.filter(t => t.dueDate <= today)} empty="Nothing due today. You’re caught up." {...taskProps} /></article>{openTasks.some(t => t.dueDate > today && crmDaysUntil(t.dueDate, today) <= 7) && <article className="glass-panel tool-panel"><p className="section-label">Next 7 days</p><TaskList tasks={openTasks.filter(t => t.dueDate > today && crmDaysUntil(t.dueDate, today) <= 7)} {...taskProps} /></article>}{candidates.length > 0 && <article className="glass-panel tool-panel"><p className="section-label">New SBRA referrals</p><p className="tool-hint">Turn a referral into a contact, opportunity, and follow-up task.</p>{candidates.map(r => <div className="crm-referral-row" key={r.id}><div><strong>{r.prospectName || "Member referral"}</strong><span>{r.need}</span></div><button className="secondary-button" onClick={() => convertReferral(r)}>Add to CRM</button></div>)}</article>}</>}
    {view === "contacts" && <ContactsView workspace={workspace} members={members} businessById={businessById} draft={contactDraft} setDraft={setContactDraft} show={form === "contact"} toggle={() => setForm(form === "contact" ? null : "contact")} submit={submitContact} importMember={importMember} search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} select={setSelectedContactId} exportCsv={exportCsv} chooseCsv={chooseCsv} csvPreview={csvPreview} importCsv={importCsv} clearCsv={() => setCsvPreview([])} />}
    {view === "pipeline" && <><div className="tools-toolbar"><button className="primary-button" onClick={() => setForm(form === "opportunity" ? null : "opportunity")}>{form === "opportunity" ? "Close" : "+ Add opportunity"}</button></div>{form === "opportunity" && <OpportunityForm draft={opportunityDraft} setDraft={setOpportunityDraft} contacts={workspace.contacts} submit={submitOpportunity} />}<div className="crm-pipeline">{crmOpportunityStages.map(stage => <section className="crm-pipeline-column" key={stage.key}><h4>{stage.label}<span>{workspace.opportunities.filter(o => !o.archivedAt && o.stage === stage.key).length}</span></h4>{workspace.opportunities.filter(o => !o.archivedAt && o.stage === stage.key).map(o => <OpportunityRow key={o.id} opportunity={o} contact={contactById.get(o.contactId)} open={() => setSelectedOpportunityId(o.id)} onStage={next => updateOpportunity(o.id, { stage: next })} />)}{!workspace.opportunities.some(o => !o.archivedAt && o.stage === stage.key) && <p className="tool-hint">No opportunities.</p>}</section>)}</div></>}
  </div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="tool-field"><span>{label}</span><span className="tool-input-wrap">{children}</span></label>; }
function Metric({ n, label }: { n: number; label: string }) { return <div className="tool-metric"><strong>{n}</strong><span>{label}</span></div>; }
function SectionHead({ label, title, button, action }: { label: string; title: string; button: string; action: () => void }) { return <div className="crm-section-head"><div><p className="section-label">{label}</p><h4>{title}</h4></div><button className="primary-button" onClick={action}>{button}</button></div>; }
function ContactDetails({ contact, update }: { contact: CrmContact; update: (p: Partial<CrmContact>) => void }) { return <article className="glass-panel tool-panel"><p className="section-label">Contact details</p><div className="tool-form"><Field label="Email"><input type="email" value={contact.email} onChange={e => update({ email: e.target.value })} /></Field><Field label="Phone"><input type="tel" value={contact.phone} onChange={e => update({ phone: e.target.value })} /></Field><Field label="Met at"><input value={contact.metAt} onChange={e => update({ metAt: e.target.value })} /></Field><Field label="Tags"><input value={contact.tags.join(", ")} onChange={e => update({ tags: e.target.value.split(",").map(x => x.trim()).filter(Boolean) })} /></Field><Field label="Quick note"><input value={contact.note} onChange={e => update({ note: e.target.value })} /></Field></div></article>; }
function TaskForm({ draft, setDraft, contacts, opportunities, submit }: { draft: { title: string; dueDate: string; contactId: string; opportunityId: string }; setDraft: (v: typeof draft) => void; contacts: CrmContact[]; opportunities: CrmOpportunity[]; submit: () => void }) { return <div className="tool-form crm-add-form"><Field label="Task"><input value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} /></Field><Field label="Due"><input type="date" value={draft.dueDate} onChange={e => setDraft({ ...draft, dueDate: e.target.value })} /></Field><Field label="Contact"><select value={draft.contactId} onChange={e => setDraft({ ...draft, contactId: e.target.value })}><option value="">None</option>{contacts.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Opportunity"><select value={draft.opportunityId} onChange={e => setDraft({ ...draft, opportunityId: e.target.value })}><option value="">None</option>{opportunities.filter(o => !o.archivedAt).map(o => <option key={o.id} value={o.id}>{o.title}</option>)}</select></Field><button className="primary-button" onClick={submit}>Save task</button></div>; }
function TaskList({ tasks, contacts, opportunities, today, onUpdate, onDelete, empty = "No tasks yet." }: { tasks: CrmTask[]; contacts: Map<string, CrmContact>; opportunities: CrmOpportunity[]; today: string; onUpdate: (id: string, patch: Partial<CrmTask>) => void; onDelete: (id: string) => void; empty?: string }) { if (!tasks.length) return <p className="tool-hint">{empty}</p>; return <div className="crm-task-list">{tasks.map(t => <div className={`crm-task ${t.completedAt ? "done" : t.dueDate < today ? "overdue" : ""}`} key={t.id}><input aria-label={`Complete ${t.title}`} type="checkbox" checked={Boolean(t.completedAt)} onChange={() => onUpdate(t.id, { completedAt: t.completedAt ? undefined : new Date().toISOString() })} /><div><input className="crm-task-title" value={t.title} onChange={e => onUpdate(t.id, { title: e.target.value })} /><small>{t.contactId ? contacts.get(t.contactId)?.name : "General task"}{t.opportunityId ? ` · ${opportunities.find(o => o.id === t.opportunityId)?.title ?? ""}` : ""}</small></div><input aria-label={`Due date for ${t.title}`} type="date" value={t.dueDate} onChange={e => onUpdate(t.id, { dueDate: e.target.value })} /><button className="crm-icon-button" aria-label={`Delete ${t.title}`} onClick={() => onDelete(t.id)}>×</button></div>)}</div>; }
function OpportunityForm({ draft, setDraft, contacts, submit }: { draft: { title: string; contactId: string; value: string; expectedClose: string }; setDraft: (v: typeof draft) => void; contacts: CrmContact[]; submit: () => void }) { return <article className="glass-panel tool-panel"><p className="section-label">New opportunity</p><div className="tool-form"><Field label="Name"><input value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} /></Field><Field label="Contact"><select value={draft.contactId} onChange={e => setDraft({ ...draft, contactId: e.target.value })}><option value="">Choose…</option>{contacts.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Value (optional)"><input type="number" min="0" value={draft.value} onChange={e => setDraft({ ...draft, value: e.target.value })} /></Field><Field label="Expected close"><input type="date" value={draft.expectedClose} onChange={e => setDraft({ ...draft, expectedClose: e.target.value })} /></Field></div><button className="primary-button" onClick={submit}>Add opportunity</button></article>; }
function OpportunityRow({ opportunity, contact, onStage, open }: { opportunity: CrmOpportunity; contact?: CrmContact; onStage: (s: CrmOpportunityStage) => void; open: () => void }) { return <article className="crm-opportunity-card"><button className="crm-opportunity-open" onClick={open}><strong>{opportunity.title}</strong><span>{contact?.name ?? "Unknown contact"}{opportunity.value !== null ? ` · $${opportunity.value.toLocaleString()}` : ""}</span></button><select value={opportunity.stage} onChange={e => onStage(e.target.value as CrmOpportunityStage)}>{crmOpportunityStages.map(s => <option key={s.key} value={s.key}>{s.label}</option>)}</select></article>; }
function OpportunityDetail({ opportunity, contacts, onBack, onUpdate }: { opportunity: CrmOpportunity; contacts: CrmContact[]; onBack: () => void; onUpdate: (p: Partial<CrmOpportunity>) => void }) { return <div className="tool-body"><button className="tool-back" onClick={onBack}>← Pipeline</button><article className="glass-panel tool-panel"><p className="section-label">Opportunity detail</p><div className="tool-form"><Field label="Name"><input value={opportunity.title} onChange={e => onUpdate({ title: e.target.value })} /></Field><Field label="Contact"><select value={opportunity.contactId} onChange={e => onUpdate({ contactId: e.target.value })}>{contacts.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Stage"><select value={opportunity.stage} onChange={e => onUpdate({ stage: e.target.value as CrmOpportunityStage })}>{crmOpportunityStages.map(s => <option key={s.key} value={s.key}>{s.label}</option>)}</select></Field><Field label="Expected close"><input type="date" value={opportunity.expectedClose} onChange={e => onUpdate({ expectedClose: e.target.value })} /></Field><Field label="Value"><input type="number" min="0" value={opportunity.value ?? ""} onChange={e => onUpdate({ value: e.target.value ? Number(e.target.value) : null })} /></Field><Field label="Notes"><textarea value={opportunity.note} onChange={e => onUpdate({ note: e.target.value })} /></Field></div></article><article className="glass-panel tool-panel"><p className="section-label">Stage history</p>{opportunity.stageHistory.length ? [...opportunity.stageHistory].reverse().map(h => <p key={h.id}><strong>{crmOpportunityStageLabel(h.from)} → {crmOpportunityStageLabel(h.to)}</strong> · {new Date(h.changedAt).toLocaleString()}</p>) : <p className="tool-hint">No stage changes yet.</p>}</article><button className="secondary-button crm-danger" onClick={() => { onUpdate({ archivedAt: new Date().toISOString() }); onBack(); }}>Archive opportunity</button></div>; }
function Activity({ contact, draft, setDraft, fail, save }: { contact: CrmContact; draft: { type: CrmActivityType; text: string; date: string }; setDraft: (v: typeof draft) => void; fail: (s: string) => void; save: (p: Partial<CrmContact>) => void }) { return <article className="glass-panel tool-panel"><p className="section-label">Activity history</p><div className="crm-act-types">{(Object.keys(activityMeta) as CrmActivityType[]).map(type => <button className={draft.type === type ? "tool-chip active" : "tool-chip"} key={type} onClick={() => setDraft({ ...draft, type })}>{activityMeta[type]}</button>)}</div><Field label="What happened?"><input value={draft.text} onChange={e => setDraft({ ...draft, text: e.target.value })} /></Field><div className="crm-add-actions"><input type="date" value={draft.date} onChange={e => setDraft({ ...draft, date: e.target.value })} /><button className="primary-button" onClick={() => { if (!draft.text.trim()) return fail("Describe the activity first."); save({ stage: contact.stage === "new" ? "connected" : contact.stage, activities: [{ id: createCrmId("activity"), ...draft, text: draft.text.trim() }, ...contact.activities] }); setDraft({ type: "note", text: "", date: new Date().toISOString().slice(0, 10) }); }}>Log activity</button></div>{contact.activities.map(a => <div className="crm-timeline-item" key={a.id}><span>{activityMeta[a.type]}</span><p>{a.date} · {a.text}</p></div>)}</article>; }

function ContactsView({ workspace, members, businessById, draft, setDraft, show, toggle, submit, importMember, search, setSearch, filter, setFilter, select, exportCsv, chooseCsv, csvPreview, importCsv, clearCsv }: { workspace: CrmWorkspace; members: Member[]; businessById: Map<string, Business>; draft: ContactDraft; setDraft: (v: ContactDraft) => void; show: boolean; toggle: () => void; submit: () => void; importMember: (id: string) => void; search: string; setSearch: (v: string) => void; filter: "all" | CrmContactStage; setFilter: (v: "all" | CrmContactStage) => void; select: (id: string) => void; exportCsv: () => void; chooseCsv: (f?: File) => void; csvPreview: CrmCsvPreviewRow[]; importCsv: () => void; clearCsv: () => void }) {
  const query = search.toLowerCase();
  const visible = workspace.contacts.filter(c => (filter === "all" || c.stage === filter) && (!query || `${c.name} ${c.company} ${c.email} ${c.phone}`.toLowerCase().includes(query)));
  return <>
    <div className="tools-toolbar"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search contacts…" /><button className="primary-button" onClick={toggle}>{show ? "Close" : "+ Add contact"}</button><label className="secondary-button crm-file-button">Import CSV<input type="file" accept=".csv,text/csv" onChange={e => void chooseCsv(e.target.files?.[0])} /></label>{workspace.contacts.length > 0 && <button className="secondary-button" onClick={exportCsv}>Export CSV</button>}</div>
    <div className="tools-filters"><button className={filter === "all" ? "tool-chip active" : "tool-chip"} onClick={() => setFilter("all")}>All</button>{crmContactStages.map(s => <button key={s.key} className={filter === s.key ? "tool-chip active" : "tool-chip"} onClick={() => setFilter(s.key)}>{s.label}</button>)}</div>
    {show && <article className="glass-panel tool-panel"><p className="section-label">New contact</p><div className="tool-form"><Field label="Name"><input value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /></Field><Field label="Company"><input value={draft.company} onChange={e => setDraft({ ...draft, company: e.target.value })} /></Field><Field label="Email"><input type="email" value={draft.email} onChange={e => setDraft({ ...draft, email: e.target.value })} /></Field><Field label="Phone"><input type="tel" value={draft.phone} onChange={e => setDraft({ ...draft, phone: e.target.value })} /></Field><Field label="Met at"><input value={draft.metAt} onChange={e => setDraft({ ...draft, metAt: e.target.value })} /></Field></div><div className="crm-add-actions"><button className="primary-button" onClick={submit}>Add contact</button>{members.length > 0 && <select defaultValue="" onChange={e => importMember(e.target.value)}><option value="">Or import from directory…</option>{members.map(m => <option key={m.id} value={m.id}>{m.name}{businessById.get(m.businessId) ? ` — ${businessById.get(m.businessId)?.name}` : ""}</option>)}</select>}</div></article>}
    {csvPreview.length > 0 && <article className="glass-panel tool-panel"><div className="crm-section-head"><div><p className="section-label">CSV preview</p><h4>{csvPreview.filter(r => r.status === "ready").length} ready · {csvPreview.filter(r => r.status === "duplicate").length} duplicates · {csvPreview.filter(r => r.status === "invalid").length} invalid</h4></div><div className="crm-add-actions"><button className="primary-button" onClick={importCsv}>Import new contacts</button><button className="secondary-button" onClick={clearCsv}>Cancel</button></div></div><div className="crm-csv-preview">{csvPreview.slice(0, 20).map(r => <div key={r.row} className={`crm-csv-row ${r.status}`}><strong>{r.contact.name || `Row ${r.row}`}</strong><span>{r.contact.email || r.contact.phone || "No email or phone"}</span><em>{r.reason}</em></div>)}</div>{csvPreview.length > 20 && <p className="tool-hint">Showing the first 20 rows.</p>}</article>}
    {visible.map(c => <button className="glass-panel tool-panel crm-card" key={c.id} onClick={() => select(c.id)}><div className="crm-head"><h4>{c.priority && "★ "}{c.name}{c.company && ` · ${c.company}`}</h4><span className={`crm-stage-badge stage-${c.stage}`}>{crmContactStageLabel(c.stage)}</span></div><span className="tool-hint">{c.email || c.phone || c.metAt || "Add contact details"}</span><span className="crm-open">Open →</span></button>)}
    {!visible.length && <article className="glass-panel tool-panel"><p className="tool-hint">{workspace.contacts.length ? "No contacts match these filters." : "Start with one customer or import a CSV. Name is the only required field."}</p></article>}
  </>;
}
