// Generated from https://www.sbrassociation.com/directory/pa/berks-county
// Run: node scripts/sync-sbra-directory.mjs

import type { Business, Member } from "@/lib/types";

export const sbraBusinessSeed = [
  {
    "id": "422-business-advisor",
    "name": "422 Business Advisor",
    "category": "Media",
    "description": "422 Business Advisor is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Media",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.422business.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.422business.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "cornerstone-books",
    "name": "A Mazzo Accounting",
    "category": "Accounting",
    "description": "A Mazzo Accounting is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Accounting",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.amazzoaccounting.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://irp.cdn-website.com/c49327f1/dms3rep/multi/Mazzo+logo.png",
    "memberOffer": ""
  },
  {
    "id": "ace-janitorial-llc",
    "name": "Ace Janitorial LLC",
    "category": "Commercial Cleaning",
    "description": "Ace Janitorial LLC is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Commercial Cleaning",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "https://acejanitorialberks.com/",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=acejanitorialberks.com&sz=256",
    "memberOffer": "Free Consultation"
  },
  {
    "id": "american-capital-express-llc",
    "name": "American Capital Express LLC",
    "category": "Small Business Funding Consultants - Small Business Loans",
    "description": "Bladimir Mercedes",
    "servicesOffered": "Small Business Funding Consultants - Small Business Loans",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.AmericanCapitalExpress.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.americancapitalexpress.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "american-insuring-group",
    "name": "American Insuring Group",
    "category": "Insurance",
    "description": "We specialize in small business insurance. General Liability, Workers Comp, Business Auto, etc. We represent over 24 insurance carriers to give you freedom of choice.",
    "servicesOffered": "Insurance",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.aigltd.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://lirp.cdn-website.com/43c3ee7c/dms3rep/multi/opt/AIG-EAGLE-ClearBkr5-195w.png",
    "memberOffer": ""
  },
  {
    "id": "antanavage-farbiarz-pllc",
    "name": "Antanavage Farbiarz PLLC",
    "category": "Legal Services",
    "description": "Attorney - Estate Planning, Elder Law, Small Business and Real Estate",
    "servicesOffered": "Legal Services",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.antanavagefarbiarz.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.antanavagefarbiarz.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "assured-assistance",
    "name": "Assured Assistance",
    "category": "Non-medical home care",
    "description": "Assured Assistance is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Non-medical home care",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://assuredassistance.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=assuredassistance.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "sweet-laurel",
    "name": "B2 Bistro",
    "category": "Restaurant",
    "description": "B2 Bistro is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Restaurant",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.b2bistro.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.b2bistro.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "bell-media-group",
    "name": "Bell Media Group",
    "category": "Marketing",
    "description": "Storytelling, Social Media Management, Content Creation, Design Services",
    "servicesOffered": "Marketing",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.bellmediagrp.com/",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FSzMdphXDQ8eYqngecgit_logomark.png",
    "memberOffer": "Free 15-Minute Social Media Audit Via Zoom"
  },
  {
    "id": "berkshire-investment-group",
    "name": "Berkshire Investment Group",
    "category": "Financial Advising Services",
    "description": "Berkshire Investment Group is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Financial Advising Services",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.berkshireinvestmentgroup.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.berkshireinvestmentgroup.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "binary-it-solutions",
    "name": "Binary IT Solutions",
    "category": "IT Managed Service Provider",
    "description": "Binary IT Solutions is an SBRA member serving the Berks County business community.",
    "servicesOffered": "IT Managed Service Provider",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "https://www.binaryitsolutions.tech/",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2Fg7E2CtToWmqhFhaPYAoQ_Bits-logo-png.png",
    "memberOffer": "Free Network Monitoring, Quarterly Business Review and e-mail backup<br>Monetary Value of Discount or Offer*: $125 monthly discount"
  },
  {
    "id": "birdsboro-lodge-senior-living",
    "name": "Birdsboro Lodge Senior Living",
    "category": "Senior Care Facility",
    "description": "Birdsboro Lodge Senior Living is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Senior Care Facility",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "https://birdsborolodge.com/",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=birdsborolodge.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "blue-ink-notary",
    "name": "Blue Ink Notary",
    "category": "Traveling & Online Notary Service",
    "description": "Blue Ink Notary provides, covenient, flexible and professional traveling & online notary services to residents and businesses in and around Greater Reading & Berks County. When you need your signature notarized on life's important documents, I will travel to you at a time and place that fits your schedule.",
    "servicesOffered": "Traveling & Online Notary Service",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.BlueInkNotaryPA.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2F0iS0nXzMTlG4sJlEFXC4_119220322_116427426866161_6372684072758424672_n.jpg",
    "memberOffer": "10% off in person notarizations for SBRA members"
  },
  {
    "id": "c-malcolm-smith-and-co-pc",
    "name": "C Malcolm Smith and Co PC",
    "category": "Certified Public Accountants",
    "description": "Accounting & Tax Services",
    "servicesOffered": "Certified Public Accountants",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.cmscpa.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1/forms/attachments/1mvsvVjOST2sTeNgX0RQ_CMS+logo+Brochure.jpg",
    "memberOffer": "Free Consultation"
  },
  {
    "id": "cafe-folino-breakfast-lunch",
    "name": "Café Folino Breakfast-Lunch",
    "category": "Cafe Restaurant",
    "description": "Café Folino is a brand new, upcoming café in the heart of Wyomissing Pennsylvania. At Café Folino, we’re passionate about two things: great coffee and exceptional food. We believe that every visit to our café should be a cozy and delightful experience that leaves you feeling recharged.",
    "servicesOffered": "Cafe Restaurant",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.cafefolino.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.cafefolino.com&sz=256",
    "memberOffer": "10% off the total check"
  },
  {
    "id": "core1-marketing",
    "name": "Core1 Marketing",
    "category": "Marketing Consulting",
    "description": "Core1Marketing provides the experience of a Chief Marketing Officer to Small Business Owners to help grow their business without the expense and long-term commitment of hiring full time staff.",
    "servicesOffered": "Marketing Consulting",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.core1marketing.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FKX9DrQoSaGMIir2Pujed_core1logo1.png",
    "memberOffer": "Free 1-hour Consultation - VALUE $95.00"
  },
  {
    "id": "deck-craft-custom-decks-llc",
    "name": "Deck Craft Custom Decks LLC",
    "category": "Outdoor Living Space Construction",
    "description": "Outdoor Living Space Design and Construction, Decks, Patios, Structures",
    "servicesOffered": "Outdoor Living Space Construction",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.deckcraftplus.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://irp.cdn-website.com/s/c49327f1/forms/attachments/u4BhNVJSRIOMZZ7FwcPu_Logo.jpeg?Expires=1791815283&Signature=Ijf4X9DVNEUvxnbieLThRU5gJ9lMaecB3YWqx7xFwzjjmHT-B8HEI4Axkw0EM3PJvbyn1Fbd4xIzw8PSTRJBI12CgjV-5y-cG08A1IdYehPM1FRkaPIE~ikdfjI0DakZOn9FC6MSQeKWNtUHkgC7uWlGYIT-cebqfc5eI0AOaZiFXDkUQgH1R4m12VcUIoIJe4FiCIu2sN2q~SVLn2F~d-o9S-Qas1IhoHzO0MAvjZMGm~3dokVk1~Bmba6wnOk-uXXdmEdLePHxcpELHETvYWxGuvfvMaXciqUKH4c-H72D~vvKrbt4hYJ1MsN60F0JUcYhURtHmgIKrgawMJNcag__&Key-Pair-Id=K2LZRFZUOTFRGV",
    "memberOffer": "Free Consultation"
  },
  {
    "id": "deihm-professional-services-llc",
    "name": "Deihm Professional Services, LLC",
    "category": "Business Data Consulting, Notary Services",
    "description": "Master Data Management | Impact Data Services | NMTC Compliance | Notary",
    "servicesOffered": "Business Data Consulting, Notary Services",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.deihmpro.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://irp.cdn-website.com/s/c49327f1/forms/attachments/sw7EWkkTEWmrVE9m11PF_Deihm+Professional+Services%2C+LLC+Final-05-01.jpg?Expires=1788791920&Signature=m6-GMqFZRNjuSnl-XWa2v~0Ga5QEbh69Tib4GKSn3tHJai5KV5nFwGSzDghoyYi0pbQbdSzwceicKzG3BqXq0S9StDkaHh3wu~WwYJZM~TnOvBKYpdVsDc1zYjCQTATbjRBevYI~zbC6VilATQbiRylgS-R0y6HQLPdsLt0edmr8Vxmy~BhrivLCkTol-Kf6RMsIbEuJGGiJnicMVIssmfGwRpGRdMHE2TzLsQJgEdfODJQYUolalCFQ28XHHzaY55sUbvy87aOg-TY3-VeWXVDp3tgqFTpqq7sZe3u2S0noz6S3c5yZrv~SEIOiFyVtm9H7I5qztmKpd1oZrUWi8A__&Key-Pair-Id=K2LZRFZUOTFRGV",
    "memberOffer": "10% off B2B Notary services, Free consultations"
  },
  {
    "id": "vantage-insurance",
    "name": "Diamond Credit Union",
    "category": "Banking solutions",
    "description": "Join us at Diamond Credit Union – your partner in financial success. As a not-for-profit, member-owned institution, we prioritize your prosperity. From checking accounts that earn dividends to personalized solutions during any stage of your life – whether opening your first bank account or seeking business assistance – we’re here every step of your journey. Diamond is committed to your success, ensuring that whether it’s your personal or business milestones, you have a dedicated ally. Unlike commercial banks, our profits benefit you – the more we grow, the more you gain. Elevate your financial journey with Diamond, where membership means lasting wealth and success.",
    "servicesOffered": "Banking solutions",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "https://www.diamondcu.org",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1/forms/attachments/CKrkueUVSV6TXoEKq3Gf_Diamond+Logo.png",
    "memberOffer": "Refer your friends & family to get $50 for you and $50 for them"
  },
  {
    "id": "doubletree-by-hilton",
    "name": "DoubleTree by Hilton",
    "category": "Hospitality",
    "description": "DoubleTree by Hilton is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Hospitality",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.Doubletree.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FPlfcgOXOTFWIlnotKFg1_Logo.png",
    "memberOffer": ""
  },
  {
    "id": "eldercare-collaborative",
    "name": "ElderCare Collaborative",
    "category": "Senior Services",
    "description": "Aging strategist, elder care consulting, advocacy and emotional support",
    "servicesOffered": "Senior Services",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.eldercarecollaborativepa.care",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://irp.cdn-website.com/s/c49327f1/forms/attachments/STXPhf9RKiSvInPf0D5j_ECC+JPEG.jpg?Expires=1794919407&Signature=MQgHiGRQro2V6MGNmvBxfCnklgt3EfZQKtiYDsoy7KecsRSF1DXabYZylrDAnO7q83Hg7KjBkWFnmTM0R-6AnasXrdzYX3kluu~1G6V5sDya7P64JVNVOWqEtZPZE9Ru8SPXmHgM-jq3mbkghC0DYrZ1gqEFOo~lN5MCKpEBGmMjJaeQTg-gbfPGs~H31OxKQmMT5eGNzoeHhGoV3tS8upZb6fgkXsiEBhCkBEcCj45Dec1p6hU4CMXyzLaGObXkly~YHe7sYJLCYfNOfi0jQN0~dhtpNdv02BF145lrsw4XO9EHCklteTI32wWbm0AQA9xMto0jV3r5JLYx0XP77A__&Key-Pair-Id=K2LZRFZUOTFRGV",
    "memberOffer": "All members receive a free extended initial consultation with action-oriented recommendations"
  },
  {
    "id": "emerging-entrepreneurs-academy",
    "name": "Emerging Entrepreneurs Academy",
    "category": "Business Training",
    "description": "Educate business practices",
    "servicesOffered": "Business Training",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.eeainpa.org",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.eeainpa.org&sz=256",
    "memberOffer": ""
  },
  {
    "id": "exp-realty",
    "name": "eXp Realty",
    "category": "Real Estate",
    "description": "eXp Realty is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Real Estate",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.owensowenshall.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.owensowenshall.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "fxv-digital-design",
    "name": "FXV Digital Design",
    "category": "Marketing",
    "description": "At First Financial Group®, we know that financial success is the result of discipline, hard work, and smart, informed decision-making. To build and maintain an effective financial strategy, it’s important to seek out the right people who look to understand what is important to you, guide you, and provide long-term support as you move through the various stages of your financial life.",
    "servicesOffered": "Marketing",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.fxvdigital.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2F0TIXB7l3S7ulgFKhqvjP_2020-FXV-Logo.png",
    "memberOffer": "All SBRA members receive one year of free website hosting with a new website."
  },
  {
    "id": "gks-brown-realty",
    "name": "GKS Brown Realty",
    "category": "Realty",
    "description": "Our firm provides access to some of the best financial minds in the business, with strong risk-management skills, and a full array of products and services. I will work with you to identify the right strategies to achieve and protect your goals and your dreams.",
    "servicesOffered": "Realty",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.GKSBrown.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FG7QgO3aARJW22dQ3O2uw_GKS%20Brown%20Realty.jpg",
    "memberOffer": ""
  },
  {
    "id": "go-fish-seafood",
    "name": "GO FISH SEAFOOD",
    "category": "Restaurant and Retail Seafood Market",
    "description": "Seafood Market Retail and Full Service Restaurant",
    "servicesOffered": "Restaurant and Retail Seafood Market",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.gofishseafood.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1/forms/attachments/XWEPJNoSrSLRaiHrNFFg_go+fish+logo.png",
    "memberOffer": "Free Appetizer with Entree at the Restaurant / $5 off your purchase of $30 or more at Fairgrounds Farmers Market Location ONLY"
  },
  {
    "id": "goldcamp-tax-facts",
    "name": "Goldcamp Tax Facts",
    "category": "Accounting",
    "description": "Goldcamp Tax Facts is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Accounting",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "https://taxfacts.biz/",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FBinuIIY2RAqbyrnpCPCZ_GTF%20-%20logo%20jpeg%20small.JPG",
    "memberOffer": "Free 30 minute consult for business owners."
  },
  {
    "id": "golden-rule-remodeling",
    "name": "Golden Rule Remodeling",
    "category": "Remodeling",
    "description": "Helping to … Optimize your wealth. Achieve your goals. Protect your dreams. Contact me today to discuss turning your dreams into realities.",
    "servicesOffered": "Remodeling",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.goldenruleremodelingllc.com/",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.goldenruleremodelingllc.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "good-life-companies",
    "name": "Good Life Companies",
    "category": "Financial Services",
    "description": "Disclosure Info",
    "servicesOffered": "Financial Services",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.goodlifeco.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.goodlifeco.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "grill-s-surface-shine-llc",
    "name": "Grill's Surface Shine LLC",
    "category": "Surface Refinishing and Restoration",
    "description": "Grill's Surface Shine LLC is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Surface Refinishing and Restoration",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "/sbra-mark.png",
    "memberOffer": ""
  },
  {
    "id": "growth-now-movement",
    "name": "Growth Now Movement",
    "category": "Business Podcasts",
    "description": "Growth Now Movement is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Business Podcasts",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "https://growthnowmovement.com/",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=growthnowmovement.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "hitchcock-clean-restore",
    "name": "Hitchcock Clean & Restore",
    "category": "Janitorial Cleaning, Industrial Cleaning, Mold Remediation",
    "description": "Janitorial Cleaning, Industrial Cleaning, Mold Remediation",
    "servicesOffered": "Janitorial Cleaning, Industrial Cleaning, Mold Remediation",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.TeamHitchcock.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.teamhitchcock.com&sz=256",
    "memberOffer": "Free annual carpet cleaning with two year janitorial contract. *Cleanable area over 10,000 sf."
  },
  {
    "id": "holistic-financial-services",
    "name": "Holistic Financial Services",
    "category": "Financial",
    "description": "I am a dedicated representative who delivers valuable services with a coordinated and holistic approach. I look beyond your basic financial needs and seek to optimize your assets, protections, and cash flow — and minimize your debt — now and in the future. My objective is to put you on a path to efficient wealth accumulation and Financial Balance®, while protecting the future of your loved ones or your livelihood.",
    "servicesOffered": "Financial",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.jeffreybingham.net",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FmS0NwChQ26LwcsjJJKf5_Holistic%20Financial%20Services%20Jeffrey%20Bingham.png",
    "memberOffer": ""
  },
  {
    "id": "honist-solutions-llc",
    "name": "HonIsT Solutions LLC",
    "category": "IT Service",
    "description": "HonIsT Solutions LLC is an SBRA member serving the Berks County business community.",
    "servicesOffered": "IT Service",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.honistsolutions.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.honistsolutions.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "innovation-cleaning",
    "name": "Innovation Cleaning",
    "category": "Comertial Janitorial Services",
    "description": "Comertial cleaning, carpet cleaning floor strip and wax, windows cleaning, day porter",
    "servicesOffered": "Comertial Janitorial Services",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.llcinnovationcleaning.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.llcinnovationcleaning.com&sz=256",
    "memberOffer": "Free Estimate"
  },
  {
    "id": "insperity-inc",
    "name": "Insperity Inc",
    "category": "HR Services",
    "description": "HR Services/Payroll/Insurance",
    "servicesOffered": "HR Services",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.insperity.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1/forms/attachments/uGzAozBpQ0uHPMk1WeN2_IMG_0803.png",
    "memberOffer": "Free Consultation/Business Profiles"
  },
  {
    "id": "integrity-services-and-solutions-llc",
    "name": "Integrity Services and Solutions LLC",
    "category": "Insurance and Human Resources",
    "description": "Integrity Services and Solutions LLC is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Insurance and Human Resources",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.integrityservicesandsolutions.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.integrityservicesandsolutions.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "irresistible-teams",
    "name": "Irresistible Teams",
    "category": "Coaching",
    "description": "Helping leaders and organizations thrive!",
    "servicesOffered": "Coaching",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.irresistibleteams.org",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.irresistibleteams.org&sz=256",
    "memberOffer": "Free 30 minute consultation"
  },
  {
    "id": "jbt-bank",
    "name": "JBT Bank",
    "category": "Bank",
    "description": "JBT Bank is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Bank",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.JBT.bank",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.jbt.bank&sz=256",
    "memberOffer": ""
  },
  {
    "id": "kda-tech-solutions-llc",
    "name": "KDA Tech Solutions, LLC",
    "category": "Manages Service Security Provider",
    "description": "Cyber Security, VoIP, Web Design/Hosting, Managed Services, Computer System/Network/Server Design and Implementation, Risk Assessment/Management",
    "servicesOffered": "Manages Service Security Provider",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "https://kdatechsolutions.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=kdatechsolutions.com&sz=256",
    "memberOffer": "Free Vulnerability Scan"
  },
  {
    "id": "keystone-specific-chiropractic-center",
    "name": "Keystone Specific Chiropractic Center",
    "category": "Chiropractic Services",
    "description": "Keystone Specific Chiropractic Center is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Chiropractic Services",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.keystonespecific.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.keystonespecific.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "polished-nails",
    "name": "Kinya Ramen",
    "category": "Authentic Japanese Cuisine",
    "description": "Restaurant",
    "servicesOffered": "Authentic Japanese Cuisine",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://Www.kinya.us",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.kinya.us&sz=256",
    "memberOffer": ""
  },
  {
    "id": "linda-giorgio-real-estate",
    "name": "Linda Giorgio Real Estate",
    "category": "Real Estate",
    "description": "Linda Giorgio Real Estate is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Real Estate",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "https://www.giorgiodsc.com/",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.giorgiodsc.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "lions-pride",
    "name": "Lions Pride",
    "category": "Salon spa",
    "description": "Lions Pride is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Salon spa",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "https://www.lionsprideusa.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.lionsprideusa.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "lmg-marketing-solutions",
    "name": "LMG Marketing Solutions",
    "category": "Digital Marketing",
    "description": "LMG Marketing Solutions is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Digital Marketing",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.lmgmarketingsolutions.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1/forms/attachments/jGt930L4RlwoNeSe26U2_LMG+Logo.png",
    "memberOffer": "One free year of website hosting with new website build project"
  },
  {
    "id": "matos-tire-service-llc",
    "name": "Matos Tire Service LLC",
    "category": "Tire Sales",
    "description": "Mobile roadside service and repair",
    "servicesOffered": "Tire Sales",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "https://www.instagram.com/matos_tire_service_llc/",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.instagram.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "members-1st-fcu",
    "name": "Members 1st FCU",
    "category": "Financial Credit Union",
    "description": "Members 1st FCU is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Financial Credit Union",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "https://www.members1st.org/",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.members1st.org&sz=256",
    "memberOffer": ""
  },
  {
    "id": "merry-brothers-inc",
    "name": "Merry Brothers Inc.",
    "category": "Electrical",
    "description": "Merry Brothers Inc. is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Electrical",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "/sbra-mark.png",
    "memberOffer": ""
  },
  {
    "id": "miller-law-group",
    "name": "Miller Law Group",
    "category": "Attorney",
    "description": "We specialize in small to midsized businesses, estate planning, real estate law, business law, litigation, and much more",
    "servicesOffered": "Attorney",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.millerlawgroup.net",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2F6l3nOwaLSJyOGo75DzMh_mlglogobmp%20-%20Copy.png",
    "memberOffer": "Free initial consultation"
  },
  {
    "id": "new-life-to-live-llc",
    "name": "New Life to Live LLC",
    "category": "Functional Nutrition Coaching",
    "description": "NASA-backed, FDA-cleared Air and Surface sanitation and purification devices for continuous, 24/7 decontamination for all inhabited spaces in the commercial and residential markets.",
    "servicesOffered": "Functional Nutrition Coaching",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.newlifetolive.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.newlifetolive.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "optimist-cdl-coaching",
    "name": "Optimist CDL Coaching",
    "category": "CDL Training",
    "description": "Optimist CDL Coaching is an SBRA member serving the Berks County business community.",
    "servicesOffered": "CDL Training",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "/sbra-mark.png",
    "memberOffer": ""
  },
  {
    "id": "pa-americana-regions-visitors-bureau",
    "name": "PA Americana Regions Visitors Bureau",
    "category": "Entertainment/ travel",
    "description": "PA Americana Regions Visitors Bureau is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Entertainment/ travel",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "https://visitpaamericana.com/",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=visitpaamericana.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "pagoda-apparel",
    "name": "Pagoda Apparel",
    "category": "Apparel Decoration, Small Signage and Promotional Items",
    "description": "Pagoda Apparel is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Apparel Decoration, Small Signage and Promotional Items",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.pagodaapparel.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.pagodaapparel.com&sz=256",
    "memberOffer": "10% Discount"
  },
  {
    "id": "park-road-chiropractic",
    "name": "Park Road Chiropractic",
    "category": "Chiropractor",
    "description": "Park Road Chiropractic is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Chiropractor",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.drneddc.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.drneddc.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "pennsylvania-kings",
    "name": "Pennsylvania Kings",
    "category": "Entertainment",
    "description": "Professional minor league basketball team",
    "servicesOffered": "Entertainment",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "/sbra-mark.png",
    "memberOffer": "Free Consultation"
  },
  {
    "id": "keystone-web",
    "name": "Power Marketing International",
    "category": "Marketing, Advertising, Web Design",
    "description": "We specialize in creating exceptional websites that help you GET FOUND, IMPRESS, ENGAGE and CONVERT leads and customers. We support you with services to increase website traffic and grow sales, including online advertising, SEO and social media support. Contact us to learn more!",
    "servicesOffered": "Marketing, Advertising, Web Design",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.powermarketinginternational.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2F47BJqizjQPCoz07G4Drl_PMI-Logo-White-654-Test.png",
    "memberOffer": "Member Offer: Free Google Ads Setup With Any Website Design or Redesign Project - VALUE $395.00"
  },
  {
    "id": "precision-hearing",
    "name": "Precision Hearing Aid Center",
    "category": "Hearing Aids",
    "description": "We provide hearing evaluations, fitting and service.",
    "servicesOffered": "Hearing Aids",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.precisionhac.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FdXJtIqfhTQinGPSNaT4S_PHAC_Horz_2_Logo_wo_tag_%281%29.jpg",
    "memberOffer": "10% off"
  },
  {
    "id": "precision-real-estate",
    "name": "Precision Real Estate",
    "category": "Real Estate",
    "description": "Represent buyers and sellers in real estate transactions",
    "servicesOffered": "Real Estate",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "/sbra-mark.png",
    "memberOffer": "Free Consultation"
  },
  {
    "id": "prudential-pest-control",
    "name": "Prudential Pest Control",
    "category": "Pest Control",
    "description": "Prudential Pest Control is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Pest Control",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.prudentialpest.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.prudentialpest.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "r-and-b-insurance-service",
    "name": "R and B Insurance Service",
    "category": "Insurance",
    "description": "R&B is driven to assist businesses and individuals in navigating the ever-changing insurance market. We represent all of the major insurance carriers, allowing us to remain current on all benefit offerings and provide our clients with customized solutions.",
    "servicesOffered": "Insurance",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.rbinsuranceservice.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://lirp.cdn-website.com/c49327f1/dms3rep/multi/opt/Logo-RandB-Insurance-1920w.png",
    "memberOffer": "Free no obligation reviews of current insurance benefits."
  },
  {
    "id": "reading-dermatology",
    "name": "Reading Dermatology Associates",
    "category": "Medical and Cosmetic Dermatology",
    "description": "We provide skin care for the entire family, from infants to seniors as well as cosmetic skin care to \"gently soften the aging process\".",
    "servicesOffered": "Medical and Cosmetic Dermatology",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.readingderm.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2F33yGXjyDTVK9CqGEkLk3_2019-DBD-ReadingDerm-Logo-Present-21.jpg",
    "memberOffer": "10% off of any first time cosmetic skin care service"
  },
  {
    "id": "red-patch-roofing-contracting-llc",
    "name": "Red Patch Roofing & Contracting, LLC",
    "category": "Roofing services",
    "description": "Roofing Services",
    "servicesOffered": "Roofing services",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.RedPatchRoofing.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.redpatchroofing.com&sz=256",
    "memberOffer": "Free estimates, 500 referral fee"
  },
  {
    "id": "rick-fisher-coaching",
    "name": "Rick Fisher Coaching",
    "category": "Leadership development coaching",
    "description": "Rick Fisher Coaching is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Leadership development coaching",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "/sbra-mark.png",
    "memberOffer": ""
  },
  {
    "id": "rivco",
    "name": "Rivco",
    "category": "Sign manufacture/service/install",
    "description": "Rivco is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Sign manufacture/service/install",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.rivcolucasinc.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.rivcolucasinc.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "riverfront-federal-credit-union",
    "name": "Riverfront Federal Credit Union",
    "category": "Banking",
    "description": "To be eligible to join Riverfront you must currently live, work, worship or attend school in Berks County, Pennsylvania or be a legal entity doing business in Berks County. Also eligible for membership is a current member's spouse, child, parent, sibling, grandparent, grandchild and in-law. You will need to provide proof of your eligibility. All it takes is a $5.00 deposit into a savings account.",
    "servicesOffered": "Banking",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.riverfrontfcu.org",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FifvkAdXUS6eW8TuILTJi_Riverfront%20Primary%20Logotype_Color.jpg",
    "memberOffer": "Free mousepad and cell phone sleeve with each account opening"
  },
  {
    "id": "robinson-and-associates",
    "name": "Robinson and Associates",
    "category": "Consulting",
    "description": "We provide financial consulting services to small businesses.",
    "servicesOffered": "Consulting",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://jrassociatesconsulting.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FamrufMvRgy9goaODgYJJ_RAlogolighttrans.png",
    "memberOffer": "Free initial consultation"
  },
  {
    "id": "salt-and-light-cafe",
    "name": "Salt and Light Cafe",
    "category": "Coffee Shop",
    "description": "Salt and Light Cafe is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Coffee Shop",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.sl-cafe.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FwZfAwDrTxSwDRoDQgAgg_Salt%20%26%20Light%20Cafe%20-%20background.jpg",
    "memberOffer": "10% Off"
  },
  {
    "id": "score",
    "name": "SCORE",
    "category": "Service",
    "description": "SCORE is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Service",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "https://berksschuylkill.score.org/",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=berksschuylkill.score.org&sz=256",
    "memberOffer": ""
  },
  {
    "id": "greenedge-lawn",
    "name": "Security Service Company",
    "category": "Security Systems",
    "description": "Security Service Company is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Security Systems",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.sscsince73.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2F1PAb7LkQuGpqOHzWZyMA_SSC%20FinalLogo%208-26-11.jpg",
    "memberOffer": ""
  },
  {
    "id": "sensory-concepts-orthopedic-and-medical-massage",
    "name": "Sensory Concepts Orthopedic and Medical Massage",
    "category": "Orthopedic, Medical and various other modalities of Massage",
    "description": "We provide orthopedic, therapeutic, deep tissue massages, as well as many other modalities.",
    "servicesOffered": "Orthopedic, Medical and various other modalities of Massage",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.sensoryconcepts.net",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FEIoKcn34TSWzg70G3ldZ_1506617011711-y3oo9z80v2o-916ab5883ad90ca7193373cc61e6296c.png",
    "memberOffer": ""
  },
  {
    "id": "service-360-group",
    "name": "Service 360 Group",
    "category": "Plumbing, Heating, Cooling, & Electrical Services",
    "description": "Plumbing, Electrical and HVAC Services",
    "servicesOffered": "Plumbing, Heating, Cooling, & Electrical Services",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://Www.service360group.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1/forms/attachments/wqQwFF6HS2dKsp27ud0g_Service-360-Group.jpg",
    "memberOffer": "10% off installation or replacement project"
  },
  {
    "id": "sir-speedy-printing",
    "name": "Sir Speedy Printing",
    "category": "Printing",
    "description": "Sir Speedy Printing is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Printing",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.sirspeedy.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.sirspeedy.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "small-for-small",
    "name": "Small For Small",
    "category": "Non Profit",
    "description": "Small For Small is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Non Profit",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.smallforsmall.org",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.smallforsmall.org&sz=256",
    "memberOffer": "20% OFF Platinum Membership"
  },
  {
    "id": "social-enterprise-institute-usa",
    "name": "Social Enterprise Institute USA",
    "category": "Advisory Services to Nonprofit organizations",
    "description": "Social Enterprise Institute USA is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Advisory Services to Nonprofit organizations",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://socialenterprisegroup.org",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=socialenterprisegroup.org&sz=256",
    "memberOffer": ""
  },
  {
    "id": "sottosanti-lawn-care",
    "name": "Sottosanti Lawn Care",
    "category": "Lawn Care",
    "description": "Sottosanti Lawn Care is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Lawn Care",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.sottosantilawncare.net",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.sottosantilawncare.net&sz=256",
    "memberOffer": ""
  },
  {
    "id": "sterling-life-solutions-llc",
    "name": "Sterling Life Solutions LLC",
    "category": "Transitional moving & downsizing services for seniors & consignment sales",
    "description": "Senior services, Moving, consignment sales",
    "servicesOffered": "Transitional moving & downsizing services for seniors & consignment sales",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.sterlinglifesolutions.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.sterlinglifesolutions.com&sz=256",
    "memberOffer": "Free Consultation"
  },
  {
    "id": "berks-apparel",
    "name": "Studio 413 Photo",
    "category": "Photography",
    "description": "Studio 413 Photo is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Photography",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.studio413.net",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.studio413.net&sz=256",
    "memberOffer": ""
  },
  {
    "id": "surestay-plus-by-best-western-reading-north",
    "name": "SureStay Plus by Best Western Reading North",
    "category": "Hospitality",
    "description": "We provide guest-rooms for Overnight accommodations with the following features: No-Smoking: Rooms with 2-Double Beds and No-Smoking 1-King bed with pull-out sofa beds: Amenities include: Free, Reliable, Premium & Fast Wi-Fi, 24/7 Coffee & Lemon infused ice water, Breakfast Buffet (6:30 – 9:30 am), No Pets Allowed. In -Room Amenities include: 55-inch LG Flat Screen TV w/ HD channels, Refrigerator & Microwave Oven, Coffee Maker, Hair Dryer, Iron with Ironing board; work table & chair. Fresh, Hot Breakfast Buffet includes: Scramble Eggs, Bacon/Sausage, Hot Cereal, Cold Cereal, Various Breads, Various Pastries/Danishes/Muffins, Fresh Fruits & Yogurts; plus: Beverages: Coffees, Teas, Juices, Water, & Milk; and featuring make-your-own waffles. Additionally, we have a meeting room for a variety of events & meetings for maximum of 30 people.",
    "servicesOffered": "Hospitality",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1/forms/attachments/TY18HckURK678YFq3VE7_SureStay+Plus+Logo+RGB+300+DPI.jpg",
    "memberOffer": "20% off"
  },
  {
    "id": "suzy-rae-design",
    "name": "Suzy Rae Design",
    "category": "Creative Print and Web Design",
    "description": "Suzy Rae Design is a graphic design company, established in 2004, that creates powerful and innovative designs. With over 30 years of design experience and creativity we are committed to quality service and design.",
    "servicesOffered": "Creative Print and Web Design",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "https://suzyraedesign.com/",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FiBhpDcXLQX6Ig8VitGec_SRD_Logo_2019_Standardweb.jpg",
    "memberOffer": "10% Discount on start-up business, logo, social media, website."
  },
  {
    "id": "the-kings-academy",
    "name": "The Kings Academy",
    "category": "private school",
    "description": "The Kings Academy is an SBRA member serving the Berks County business community.",
    "servicesOffered": "private school",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.kingsacademy.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FEgLbTRaAQmCUPnonbt1b_TKA-LOGO-high-quality.jpg",
    "memberOffer": "nonprofit"
  },
  {
    "id": "two-hills-consulting",
    "name": "Two Hills Consulting",
    "category": "Consulting",
    "description": "Two Hills Consulting is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Consulting",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "https://www.linkedin.com/in/terri-hill-b2915a8/",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://www.google.com/s2/favicons?domain=www.linkedin.com&sz=256",
    "memberOffer": ""
  },
  {
    "id": "ultimate-comfort-heating-cooling",
    "name": "Ultimate Comfort Heating & Cooling",
    "category": "HVAC",
    "description": "We are an HVAC company providing residential and light commercial service, maintenance, and installations. We work with people that are searching for superior customer service, experienced well trained technicians, and an honest assessment of their system and equipment and are only finding the exact opposite. By teaching staff to treat every customer like a close friend or family we provide an air of trust with everyone they interact even when they have had bad contractor experiences in the past.",
    "servicesOffered": "HVAC",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://www.ultimatecomforthc.com",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2Fe2gyblRCR5OphRymWQbX_Logo%20only%20tif.PNG",
    "memberOffer": "10% off any service up to a maximum of $500"
  },
  {
    "id": "us-health-advisors-evan-markwood",
    "name": "US Health Advisors Evan Markwood",
    "category": "Health Insurance-Individuals •Families •Small Business",
    "description": "Health Insurance is expensive! And I help contractors, self employed, individuals and families understand all of their options as to the very best protection for a given time, budget, and situation, then securing coverage at the very lowest cost!",
    "servicesOffered": "Health Insurance-Individuals •Families •Small Business",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "http://ushagent.com/evanmarkwood",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2Fs9IQvJ2TRMiVksTn65zm_Logo%20United.jpg",
    "memberOffer": "free consultation, $100 Award for your referrals I'm able to help"
  },
  {
    "id": "will-omlor-eos-implementer",
    "name": "Will Omlor, EOS Implementer",
    "category": "Business Coaching",
    "description": "Complete system with simple, practical tools to help business owners and leadership teams get more out of the business",
    "servicesOffered": "Business Coaching",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "https://image-res-platform.s3.amazonaws.com/c49327f1/forms/attachments/T9IrIKTSEqmsO8jpnIQl_Blue+and+Orange+Full.png",
    "memberOffer": ""
  },
  {
    "id": "windsor-inn",
    "name": "Windsor Inn",
    "category": "Restaurant",
    "description": "Windsor Inn is an SBRA member serving the Berks County business community.",
    "servicesOffered": "Restaurant",
    "referralsWanted": "Open to relevant community introductions.",
    "website": "",
    "address": "",
    "city": "Berks County, PA",
    "tier": "small",
    "logo": "/sbra-mark.png",
    "memberOffer": ""
  }
] satisfies Business[];

export const sbraMemberSeed = [
  {
    "id": "tom-alvarez",
    "businessId": "precision-hearing",
    "name": "Adam Wentling",
    "title": "SBRA Member",
    "email": "adam@precisionhac.com",
    "phone": "610-779-3205",
    "bio": "We provide hearing evaluations, fitting and service.",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FA7CB0UP2R3qeFVsZhYcC_AdamWentlingProfile.jpg"
  },
  {
    "id": "maya-chen",
    "businessId": "keystone-web",
    "name": "Alan Robezzoli",
    "title": "SBRA Member",
    "email": "alanr@powermarketinginternational.com",
    "phone": "484-297-6395",
    "bio": "We specialize in creating exceptional websites that help you GET FOUND, IMPRESS, ENGAGE and CONVERT leads and customers. We support you with services to increase website traffic and grow sales, including online advertising, SEO and social media support. Contact us to learn more!",
    "isOwner": false,
    "photo": "https://lirp.cdn-website.com/43c3ee7c/dms3rep/multi/opt/Alan-Robezzoli-HappyPhoto-Wht2-384w.png"
  },
  {
    "id": "andrew-sonon-honist-solutions-llc",
    "businessId": "honist-solutions-llc",
    "name": "Andrew Sonon",
    "title": "SBRA Member",
    "email": "asonon@honistsolutions.com",
    "phone": "484-272-7240",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "betsy-brooks-r-and-b-insurance-service",
    "businessId": "r-and-b-insurance-service",
    "name": "Betsy Brooks",
    "title": "SBRA Member",
    "email": "betsyb@rbinsuranceservice.com",
    "phone": "717-798-6568",
    "bio": "R&B is driven to assist businesses and individuals in navigating the ever-changing insurance market. We represent all of the major insurance carriers, allowing us to remain current on all benefit offerings and provide our clients with customized solutions.",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "beverly-whipple-the-kings-academy",
    "businessId": "the-kings-academy",
    "name": "Beverly Whipple",
    "title": "SBRA Member",
    "email": "mgoodman@kingsacademy.com",
    "phone": "610-926-9639",
    "bio": "",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2F3xXwc7cHR5KjP53F02is_Michelle%203.jpg"
  },
  {
    "id": "bill-haley-422-business-advisor",
    "businessId": "422-business-advisor",
    "name": "Bill Haley",
    "title": "SBRA Member",
    "email": "bill@422business.com",
    "phone": "610-324-0658",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "bill-moss-keystone-specific-chiropractic-center",
    "businessId": "keystone-specific-chiropractic-center",
    "name": "Bill Moss",
    "title": "SBRA Member",
    "email": "Info@keystonespecific.com",
    "phone": "610-741-6700",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "bladimir-mercedes-american-capital-express-llc",
    "businessId": "american-capital-express-llc",
    "name": "Bladimir Mercedes",
    "title": "SBRA Member",
    "email": "blad@americancapitalexpress.com",
    "phone": "516-323-7860",
    "bio": "Bladimir Mercedes",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "bradley-o-reilly-lions-pride",
    "businessId": "lions-pride",
    "name": "Bradley O'Reilly",
    "title": "SBRA Member",
    "email": "Lionspridespa@gmail.com",
    "phone": "484-860-6336",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "brian-klein-blue-ink-notary",
    "businessId": "blue-ink-notary",
    "name": "Brian Klein",
    "title": "SBRA Member",
    "email": "bkleinnotary@gmail.com",
    "phone": "484-509-1405",
    "bio": "Blue Ink Notary provides, covenient, flexible and professional traveling & online notary services to residents and businesses in and around Greater Reading & Berks County. When you need your signature notarized on life's important documents, I will travel to you at a time and place that fits your schedule.",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1/forms/attachments/vlH2OPqBTOAS6Noq04pP_Brian+Klein_6567aq.jpg"
  },
  {
    "id": "bryan-guzman-innovation-cleaning",
    "businessId": "innovation-cleaning",
    "name": "Bryan Guzman",
    "title": "SBRA Member",
    "email": "Info@llcinnovationcleaning.com",
    "phone": "610-780-7068",
    "bio": "Comertial cleaning, carpet cleaning floor strip and wax, windows cleaning, day porter",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "bryant-lucas-rivco",
    "businessId": "rivco",
    "name": "Bryant Lucas",
    "title": "SBRA Member",
    "email": "Bryant@rivcolucasinc.com",
    "phone": "610-698-2405",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "carolann-westendorp-jbt-bank",
    "businessId": "jbt-bank",
    "name": "Carolann Westendorp",
    "title": "SBRA Member",
    "email": "cwestendorp@jbt.bank",
    "phone": "610-413-9083",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "chris-gregg-birdsboro-lodge-senior-living",
    "businessId": "birdsboro-lodge-senior-living",
    "name": "Chris Gregg",
    "title": "SBRA Member",
    "email": "Bmanor6740@yahoo.com",
    "phone": "610-575-0851",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "christine-kreisher-irresistible-teams",
    "businessId": "irresistible-teams",
    "name": "Christine Kreisher",
    "title": "SBRA Member",
    "email": "christinekreisher@gmail.com",
    "phone": "610-636-8235",
    "bio": "Helping leaders and organizations thrive!",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "connor-delaney-good-life-companies",
    "businessId": "good-life-companies",
    "name": "Connor Delaney",
    "title": "SBRA Member",
    "email": "conor.delaney@goodlifefa.com",
    "phone": "610-898-6927",
    "bio": "Disclosure Info",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "crystal-seitz-pa-americana-regions-visitors-bureau",
    "businessId": "pa-americana-regions-visitors-bureau",
    "name": "Crystal Seitz",
    "title": "SBRA Member",
    "email": "crystal@visitpaamericana.com",
    "phone": "610-375-4085",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "daniel-santos-pennsylvania-kings",
    "businessId": "pennsylvania-kings",
    "name": "Daniel Santos",
    "title": "SBRA Member",
    "email": "Pakingstbl@gmail.com",
    "phone": "484-772-6069",
    "bio": "Professional minor league basketball team",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "david-ross-american-insuring-group",
    "businessId": "american-insuring-group",
    "name": "David Ross",
    "title": "SBRA Member",
    "email": "david@aigltd.com",
    "phone": "610-775-3848",
    "bio": "We specialize in small business insurance. General Liability, Workers Comp, Business Auto, etc. We represent over 24 insurance carriers to give you freedom of choice.",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2Fb2Lrx1aQXyHz01CjtJQw_WIN_20210520_10_52_10_Pro.jpg"
  },
  {
    "id": "david-souvannarath-ace-janitorial-llc",
    "businessId": "ace-janitorial-llc",
    "name": "David Souvannarath",
    "title": "SBRA Member",
    "email": "1acejanitorial@gmail.com",
    "phone": "610-931-1285",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "deb-miller-doubletree-by-hilton",
    "businessId": "doubletree-by-hilton",
    "name": "Deb Miller",
    "title": "SBRA Member",
    "email": "deb.miller@hilton.com",
    "phone": "267-295-7219",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "dele-olaewe-pagoda-apparel",
    "businessId": "pagoda-apparel",
    "name": "Dele Olaewe",
    "title": "SBRA Member",
    "email": "dele@pagodaapparel.com",
    "phone": "610-457-3300",
    "bio": "",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FKmmEqqP0S8mjYSwgKPlY_Dad%27s%20pic.jpg"
  },
  {
    "id": "dele-olaewe-small-for-small",
    "businessId": "small-for-small",
    "name": "Dele Olaewe",
    "title": "SBRA Member",
    "email": "dele@smallforsmall",
    "phone": "610-864-0806",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "diane-klinger-integrity-services-and-solutions-llc",
    "businessId": "integrity-services-and-solutions-llc",
    "name": "Diane Klinger",
    "title": "SBRA Member",
    "email": "diane@integrityservicesandsolutions.com",
    "phone": "610-939-9593",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "ari-rivera",
    "businessId": "berks-apparel",
    "name": "Don Carrick",
    "title": "SBRA Member",
    "email": "don@studio413.net",
    "phone": "610-698-2604",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "emmanuel-mercado-salt-and-light-cafe",
    "businessId": "salt-and-light-cafe",
    "name": "Emmanuel Mercado",
    "title": "SBRA Member",
    "email": "cafesaltlight@gmail.com",
    "phone": "‪484-772-8188",
    "bio": "",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FIRkkCrJ0QvLt58uWHtnh_Headshot.PNG"
  },
  {
    "id": "eric-epler-golden-rule-remodeling",
    "businessId": "golden-rule-remodeling",
    "name": "Eric Epler",
    "title": "SBRA Member",
    "email": "eric@goldenruleremodelingllc.com",
    "phone": "484-794-8985",
    "bio": "Helping to … Optimize your wealth. Achieve your goals. Protect your dreams. Contact me today to discuss turning your dreams into realities.",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "evan-markwood-us-health-advisors-evan-markwood",
    "businessId": "us-health-advisors-evan-markwood",
    "name": "Evan Markwood",
    "title": "SBRA Member",
    "email": "evan.markwood@ushadvisors.com",
    "phone": "301-442-5106",
    "bio": "Health Insurance is expensive! And I help contractors, self employed, individuals and families understand all of their options as to the very best protection for a given time, budget, and situation, then securing coverage at the very lowest cost!",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1/forms/attachments/rzKOMe8gTJmZLccPCV91_headshot+2023.jpg"
  },
  {
    "id": "fabrizio-folino-cafe-folino-breakfast-lunch",
    "businessId": "cafe-folino-breakfast-lunch",
    "name": "Fabrizio Folino",
    "title": "SBRA Member",
    "email": "gfolino@comcast.net",
    "phone": "484-709-2047",
    "bio": "Café Folino is a brand new, upcoming café in the heart of Wyomissing Pennsylvania. At Café Folino, we’re passionate about two things: great coffee and exceptional food. We believe that every visit to our café should be a cozy and delightful experience that leaves you feeling recharged.",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "francisco-matos-matos-tire-service-llc",
    "businessId": "matos-tire-service-llc",
    "name": "Francisco Matos",
    "title": "SBRA Member",
    "email": "Matostireservice1@gmail.com",
    "phone": "215-687-5692",
    "bio": "Mobile roadside service and repair",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "frank-grill-grill-s-surface-shine-llc",
    "businessId": "grill-s-surface-shine-llc",
    "name": "Frank Grill",
    "title": "SBRA Member",
    "email": "",
    "phone": "610-301-1128",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "freddy-vasquez-fxv-digital-design",
    "businessId": "fxv-digital-design",
    "name": "Freddy Vasquez",
    "title": "SBRA Member",
    "email": "fred@fxvdigital.com",
    "phone": "484-509-4285",
    "bio": "At First Financial Group®, we know that financial success is the result of discipline, hard work, and smart, informed decision-making. To build and maintain an effective financial strategy, it’s important to seek out the right people who look to understand what is important to you, guide you, and provide long-term support as you move through the various stages of your financial life.",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FopL9Dil0QGGLldrwAJwA_Freddy_052.Final version.jpg"
  },
  {
    "id": "gary-seibert-emerging-entrepreneurs-academy",
    "businessId": "emerging-entrepreneurs-academy",
    "name": "Gary Seibert",
    "title": "SBRA Member",
    "email": "gseibert@sbrassociation.com",
    "phone": "484-333-3270",
    "bio": "Educate business practices",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "gina-hurwitz-windsor-inn",
    "businessId": "windsor-inn",
    "name": "Gina Hurwitz",
    "title": "SBRA Member",
    "email": "gegechef@aol.com",
    "phone": "484-651-3895",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "heather-clark-go-fish-seafood",
    "businessId": "go-fish-seafood",
    "name": "Heather Clark",
    "title": "SBRA Member",
    "email": "clarkh9@me.com",
    "phone": "610-763-9120",
    "bio": "Seafood Market Retail and Full Service Restaurant",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "j-randall-miller-berkshire-investment-group",
    "businessId": "berkshire-investment-group",
    "name": "J. Randall Miller",
    "title": "SBRA Member",
    "email": "Bryan.stephen@lpl.com",
    "phone": "610-371-0665",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "james-s-reeb-social-enterprise-institute-usa",
    "businessId": "social-enterprise-institute-usa",
    "name": "James S. Reeb",
    "title": "SBRA Member",
    "email": "reebj@socialenterprisegroup.org",
    "phone": "717-471-7687",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "jay-calandra-precision-real-estate",
    "businessId": "precision-real-estate",
    "name": "Jay Calandra",
    "title": "SBRA Member",
    "email": "calandrahomes@gmail.com",
    "phone": "610-442-2606",
    "bio": "Represent buyers and sellers in real estate transactions",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "jeffrey-bingham-holistic-financial-services",
    "businessId": "holistic-financial-services",
    "name": "Jeffrey Bingham",
    "title": "SBRA Member",
    "email": "jeffrey@holisticfinancial.services",
    "phone": "610-655-5140",
    "bio": "I am a dedicated representative who delivers valuable services with a coordinated and holistic approach. I look beyond your basic financial needs and seek to optimize your assets, protections, and cash flow — and minimize your debt — now and in the future. My objective is to put you on a path to efficient wealth accumulation and Financial Balance®, while protecting the future of your loved ones or your livelihood.",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2F5BlZMtjnQ5iXbFdn8n0k_Jeffrey%20Bingham.jpg"
  },
  {
    "id": "jennifer-deck-members-1st-fcu",
    "businessId": "members-1st-fcu",
    "name": "Jennifer Deck",
    "title": "SBRA Member",
    "email": "deckj@members1st.org",
    "phone": "223-895-0511",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "jennifer-larsh-new-life-to-live-llc",
    "businessId": "new-life-to-live-llc",
    "name": "Jennifer Larsh",
    "title": "SBRA Member",
    "email": "jen@newlifetolive.com",
    "phone": "484-706-1260",
    "bio": "NASA-backed, FDA-cleared Air and Surface sanitation and purification devices for continuous, 24/7 decontamination for all inhabited spaces in the commercial and residential markets.",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "jessica-king-eldercare-collaborative",
    "businessId": "eldercare-collaborative",
    "name": "Jessica King",
    "title": "SBRA Member",
    "email": "jessica@eccpa.care",
    "phone": "484-222-8678",
    "bio": "Aging strategist, elder care consulting, advocacy and emotional support",
    "isOwner": false,
    "photo": "https://irp.cdn-website.com/s/c49327f1/forms/attachments/gCKZlnStyMLbjTMZgYNg_JessicaKing.jpg.jpg?Expires=1794919407&Signature=QT5ohp1Z6q~fLhXk5FYvvx8srTCM9J6HqX0lZwnCF2E84bU~evOZCL2rs3uE0~vffQchG9v9f57FvmjZa9Ldg0vovB0eqF0WdxTU326LtGJxU~CR5BuuEQArjwqjp80nKUjS5AzKghfeEr0wyH~oa1DWl2mYn5Seqrg2RkZPtm4hFFA~p1jnTes1AvCQX7yJAm38Q2gUZXNITSZTxp3b6VEaRTJQwAxC1MHa~8FditVy~4wF1tfJWkb9ECfBmEUZ8DVcAARNdbg19iJHY04v-R-wLWY-rAnE3plSSmbrIvC8lx6kNcDcyPSltYVUw-P1fDi~ArWmNv6j7Tl8WwHzpQ__&Key-Pair-Id=K2LZRFZUOTFRGV"
  },
  {
    "id": "sofia-martinez",
    "businessId": "polished-nails",
    "name": "Jevan Chen",
    "title": "SBRA Member",
    "email": "wyomissing@kinya.us",
    "phone": "610-743-5829",
    "bio": "Restaurant",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "noah-patel",
    "businessId": "greenedge-lawn",
    "name": "Jim Long",
    "title": "SBRA Member",
    "email": "jim.long@SSCsince73.com",
    "phone": "800-232-2500",
    "bio": "",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2Fn8sDoeZiTJaJZXf0SrcG_Jim%20Long%20pic.jpg"
  },
  {
    "id": "joe-demarte-sir-speedy-printing",
    "businessId": "sir-speedy-printing",
    "name": "Joe DeMarte",
    "title": "SBRA Member",
    "email": "jdemarte@comcast.net",
    "phone": "610-670-2090",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "john-robinson-robinson-and-associates",
    "businessId": "robinson-and-associates",
    "name": "John Robinson",
    "title": "SBRA Member",
    "email": "1.johnrobinson@comcast.net",
    "phone": "610-670-9600",
    "bio": "We provide financial consulting services to small businesses.",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2Fn8aCYMHR7CMtOaq8zkWs_John%20Robinson%20Headshot.jpg"
  },
  {
    "id": "john-s-sardella-c-malcolm-smith-and-co-pc",
    "businessId": "c-malcolm-smith-and-co-pc",
    "name": "John S Sardella",
    "title": "SBRA Member",
    "email": "jsardella@cmscpa.com",
    "phone": "610-375-6330",
    "bio": "Accounting & Tax Services",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1/forms/attachments/sRKC58MaQNydf1vhmeGH_Group+Shot+CMS.jpg"
  },
  {
    "id": "judy-brown-gks-brown-realty",
    "businessId": "gks-brown-realty",
    "name": "Judy Brown",
    "title": "SBRA Member",
    "email": "judybrownsellshomes@comcast.net",
    "phone": "484-220-1000",
    "bio": "Our firm provides access to some of the best financial minds in the business, with strong risk-management skills, and a full array of products and services. I will work with you to identify the right strategies to achieve and protect your goals and your dreams.",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FX9wc16dzRF6ol8aIM8gq_Judy%20Brown.jpg"
  },
  {
    "id": "justin-schenck-growth-now-movement",
    "businessId": "growth-now-movement",
    "name": "Justin Schenck",
    "title": "SBRA Member",
    "email": "justin@growthnowmovement.com",
    "phone": "856-625-6176",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "keith-barbour-kda-tech-solutions-llc",
    "businessId": "kda-tech-solutions-llc",
    "name": "Keith Barbour",
    "title": "SBRA Member",
    "email": "kbarbour@kdatechsolutions.com",
    "phone": "717-912-4796",
    "bio": "Cyber Security, VoIP, Web Design/Hosting, Managed Services, Computer System/Network/Server Design and Implementation, Risk Assessment/Management",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "keith-harnish-ultimate-comfort-heating-cooling",
    "businessId": "ultimate-comfort-heating-cooling",
    "name": "Keith Harnish",
    "title": "SBRA Member",
    "email": "kharnish@ultimatecomforthc.com",
    "phone": "610-750-8314",
    "bio": "We are an HVAC company providing residential and light commercial service, maintenance, and installations. We work with people that are searching for superior customer service, experienced well trained technicians, and an honest assessment of their system and equipment and are only finding the exact opposite. By teaching staff to treat every customer like a close friend or family we provide an air of trust with everyone they interact even when they have had bad contractor experiences in the past.",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FVgaRq6t6TwOKQ4EnDjAe_Head%20shot.JPG"
  },
  {
    "id": "kimberley-quanquin-sterling-life-solutions-llc",
    "businessId": "sterling-life-solutions-llc",
    "name": "Kimberley Quanquin",
    "title": "SBRA Member",
    "email": "mbond@sterlinglifesolutions.com",
    "phone": "484-220-3743",
    "bio": "Senior services, Moving, consignment sales",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2Fop7G4skRmOgNtSa5JQAo_WIN_20211117_08_35_07_Pro%20%283%29.jpg"
  },
  {
    "id": "kritina-mccoy-riverfront-federal-credit-union",
    "businessId": "riverfront-federal-credit-union",
    "name": "Kritina McCoy",
    "title": "SBRA Member",
    "email": "Kmccoy@riverfrontfcu.org",
    "phone": "484-345-3116",
    "bio": "To be eligible to join Riverfront you must currently live, work, worship or attend school in Berks County, Pennsylvania or be a legal entity doing business in Berks County. Also eligible for membership is a current member's spouse, child, parent, sibling, grandparent, grandchild and in-law. You will need to provide proof of your eligibility. All it takes is a $5.00 deposit into a savings account.",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "larry-miller-jr-miller-law-group",
    "businessId": "miller-law-group",
    "name": "Larry Miller Jr.",
    "title": "SBRA Member",
    "email": "lmiller@millerlawgroup.net",
    "phone": "610-670-9000",
    "bio": "We specialize in small to midsized businesses, estate planning, real estate law, business law, litigation, and much more",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FMhWLaaxQSPuVSJoYzVXO_PBS_6573.jpg"
  },
  {
    "id": "limarys-rodriguez-lmg-marketing-solutions",
    "businessId": "lmg-marketing-solutions",
    "name": "Limarys Rodriguez",
    "title": "SBRA Member",
    "email": "info@lmgmarketingsolutions.com",
    "phone": "484-575-1564",
    "bio": "",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1/forms/attachments/ibmojd7rRXiwgKLxH4Mg_Limarys_Rodriguez_headshot.JPG"
  },
  {
    "id": "linda-giorgio-linda-giorgio-real-estate",
    "businessId": "linda-giorgio-real-estate",
    "name": "Linda Giorgio",
    "title": "SBRA Member",
    "email": "linda@giorgiodsc.com",
    "phone": "484-432-9550",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "lu-ann-seyler-hitchcock-clean-restore",
    "businessId": "hitchcock-clean-restore",
    "name": "Lu Ann Seyler",
    "title": "SBRA Member",
    "email": "luann@teamhitchcock.com",
    "phone": "610-944-0433",
    "bio": "Janitorial Cleaning, Industrial Cleaning, Mold Remediation",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FAmJRPVc3S465BSI3v4lL_IMG_4546_sm.jpg"
  },
  {
    "id": "mark-kramer-core1-marketing",
    "businessId": "core1-marketing",
    "name": "Mark Kramer",
    "title": "SBRA Member",
    "email": "markk@core1marketing.com",
    "phone": "484-797-4771",
    "bio": "Core1Marketing provides the experience of a Chief Marketing Officer to Small Business Owners to help grow their business without the expense and long-term commitment of hiring full time staff.",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FYtOUXCeJSuuMZoquXdMJ_Mark%20Kramer_041%20Web.jpg"
  },
  {
    "id": "matthew-merry-merry-brothers-inc",
    "businessId": "merry-brothers-inc",
    "name": "Matthew Merry",
    "title": "SBRA Member",
    "email": "merrybrothersllc@yahoo.com",
    "phone": "484-261-5590",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "ned-devlin-park-road-chiropractic",
    "businessId": "park-road-chiropractic",
    "name": "Ned Devlin",
    "title": "SBRA Member",
    "email": "drned@comcast.net",
    "phone": "610-236-0200",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "patrick-readdy-insperity-inc",
    "businessId": "insperity-inc",
    "name": "Patrick Readdy",
    "title": "SBRA Member",
    "email": "patrick.readdy@insperity.com",
    "phone": "610-301-2862",
    "bio": "HR Services/Payroll/Insurance",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1/forms/attachments/OBzY6ORGCymjpdp3drvA_IMG_0084.jpeg"
  },
  {
    "id": "pedro-rosario-optimist-cdl-coaching",
    "businessId": "optimist-cdl-coaching",
    "name": "Pedro Rosario",
    "title": "SBRA Member",
    "email": "optimistcdlcoaching@gmail.com",
    "phone": "484-529-9176",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "peter-kostick-score",
    "businessId": "score",
    "name": "Peter Kostick",
    "title": "SBRA Member",
    "email": "pgkostick@comcast.net",
    "phone": "484-577-9791",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "richard-fisher-rick-fisher-coaching",
    "businessId": "rick-fisher-coaching",
    "name": "Richard Fisher",
    "title": "SBRA Member",
    "email": "freerick2@gmail.com",
    "phone": "484 824-2444",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "rob-landis-binary-it-solutions",
    "businessId": "binary-it-solutions",
    "name": "Rob Landis",
    "title": "SBRA Member",
    "email": "rob@binaryitsolutions.tech",
    "phone": "610-320-2628",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "robert-glasner-deck-craft-custom-decks-llc",
    "businessId": "deck-craft-custom-decks-llc",
    "name": "Robert Glasner",
    "title": "SBRA Member",
    "email": "Rglasner@deckcraftcustomdecks.com",
    "phone": "610-310-1947",
    "bio": "Outdoor Living Space Design and Construction, Decks, Patios, Structures",
    "isOwner": false,
    "photo": "https://irp.cdn-website.com/s/c49327f1/forms/attachments/XEJHiqtAQeSJn185EiHs_IMG_5056.JPG?Expires=1791815283&Signature=PUU0m2l3FJpbhP7kAfsAOX4njQJVelm4mL7cFGO~eQ8v3yqW369UzfQlW737MCsHNKJHcHLsOhyBNecxEs425vb9jZIhbww5KPbGS5B~AEjIJh6sQxSWibPoMJ8okHQrFXYe1NT56eNWs~ecsBYlcm7~xTMBJG4GM4J1zzC5RltdCf7zCvg8ayVYVEbn6n~ENE2aiUQnEoHaTNNE40e8zHk7AW27mOO7vGoDJ532s7nDAqS6d-bCXNPpIGClbMmJ47yhHEOo0Fbpj-3Krm68tj2hyxukkYWVyQnADrrN5Lldxp89OBOrZMiHsxcAqG4rYTmz8LeGEBmWMn3fV02d~A__&Key-Pair-Id=K2LZRFZUOTFRGV"
  },
  {
    "id": "rochelle-owens-exp-realty",
    "businessId": "exp-realty",
    "name": "Rochelle Owens",
    "title": "SBRA Member",
    "email": "rochellesellshouses@gmail.com",
    "phone": "610-587-3305",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "russell-e-farbiarz-esq-antanavage-farbiarz-pllc",
    "businessId": "antanavage-farbiarz-pllc",
    "name": "Russell E. Farbiarz Esq.",
    "title": "SBRA Member",
    "email": "rfarbiarz@afalawfirm.com",
    "phone": "610-562-2000",
    "bio": "Attorney - Estate Planning, Elder Law, Small Business and Real Estate",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "ryan-ellenberger-prudential-pest-control",
    "businessId": "prudential-pest-control",
    "name": "Ryan Ellenberger",
    "title": "SBRA Member",
    "email": "ryane@prudentialpest.com",
    "phone": "484-401-4361",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "sabastian-sottosanti-sottosanti-lawn-care",
    "businessId": "sottosanti-lawn-care",
    "name": "Sabastian Sottosanti",
    "title": "SBRA Member",
    "email": "sebastiansottosanti0771@gmail.com",
    "phone": "610-914-2522",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "sam-kensinger-red-patch-roofing-contracting-llc",
    "businessId": "red-patch-roofing-contracting-llc",
    "name": "Sam Kensinger",
    "title": "SBRA Member",
    "email": "Sam@RedPatchRoofing.com",
    "phone": "910-728-0212",
    "bio": "Roofing Services",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "sandra-wagner-sensory-concepts-orthopedic-and-medical-massage",
    "businessId": "sensory-concepts-orthopedic-and-medical-massage",
    "name": "Sandra Wagner",
    "title": "SBRA Member",
    "email": "sensoryconcepts@aol.com",
    "phone": "484-509-5505",
    "bio": "We provide orthopedic, therapeutic, deep tissue massages, as well as many other modalities.",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FQHApZybdSlWZW2lFOKwc_SandyW.JPG"
  },
  {
    "id": "scott-kolb-service-360-group",
    "businessId": "service-360-group",
    "name": "Scott Kolb",
    "title": "SBRA Member",
    "email": "inquiry@service360group.com",
    "phone": "610-370-9907",
    "bio": "Plumbing, Electrical and HVAC Services",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "sherry-kutz-assured-assistance",
    "businessId": "assured-assistance",
    "name": "Sherry Kutz",
    "title": "SBRA Member",
    "email": "sherry@assuredassistance.com",
    "phone": "610-796-4737",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "susan-goldcamp-goldcamp-tax-facts",
    "businessId": "goldcamp-tax-facts",
    "name": "Susan Goldcamp",
    "title": "SBRA Member",
    "email": "info@taxfacts.biz",
    "phone": "610-927-3030",
    "bio": "",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FBinuIIY2RAqbyrnpCPCZ_GTF%20-%20logo%20jpeg%20small.JPG"
  },
  {
    "id": "suzy-lysczek-suzy-rae-design",
    "businessId": "suzy-rae-design",
    "name": "Suzy Lysczek",
    "title": "SBRA Member",
    "email": "suzy@suzyraedesign.com",
    "phone": "610-376-1128",
    "bio": "Suzy Rae Design is a graphic design company, established in 2004, that creates powerful and innovative designs. With over 30 years of design experience and creativity we are committed to quality service and design.",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FzGD8NWpfQFmltxxzCu2d_Suzypict.jpg"
  },
  {
    "id": "tara-deihm-deihm-professional-services-llc",
    "businessId": "deihm-professional-services-llc",
    "name": "Tara Deihm",
    "title": "SBRA Member",
    "email": "tdeihm@deihmpro.com",
    "phone": "717-997-8142",
    "bio": "Master Data Management | Impact Data Services | NMTC Compliance | Notary",
    "isOwner": false,
    "photo": "https://irp.cdn-website.com/s/c49327f1/forms/attachments/XEJHiqtAQeSJn185EiHs_IMG_5056.JPG?Expires=1791815283&Signature=PUU0m2l3FJpbhP7kAfsAOX4njQJVelm4mL7cFGO~eQ8v3yqW369UzfQlW737MCsHNKJHcHLsOhyBNecxEs425vb9jZIhbww5KPbGS5B~AEjIJh6sQxSWibPoMJ8okHQrFXYe1NT56eNWs~ecsBYlcm7~xTMBJG4GM4J1zzC5RltdCf7zCvg8ayVYVEbn6n~ENE2aiUQnEoHaTNNE40e8zHk7AW27mOO7vGoDJ532s7nDAqS6d-bCXNPpIGClbMmJ47yhHEOo0Fbpj-3Krm68tj2hyxukkYWVyQnADrrN5Lldxp89OBOrZMiHsxcAqG4rYTmz8LeGEBmWMn3fV02d~A__&Key-Pair-Id=K2LZRFZUOTFRGV"
  },
  {
    "id": "terri-hill-two-hills-consulting",
    "businessId": "two-hills-consulting",
    "name": "Terri Hill",
    "title": "SBRA Member",
    "email": "terri@twohills.consulting",
    "phone": "484-332-8014",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "jada-lee",
    "businessId": "cornerstone-books",
    "name": "Tony Mazzo",
    "title": "SBRA Member",
    "email": "amazzoaccounting@comcast.net",
    "phone": "610-775-9216",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "vijay-joshi-surestay-plus-by-best-western-reading-north",
    "businessId": "surestay-plus-by-best-western-reading-north",
    "name": "Vijay Joshi",
    "title": "SBRA Member",
    "email": "ReadingHotelLLC@gmail.com",
    "phone": "610-371-0500",
    "bio": "We provide guest-rooms for Overnight accommodations with the following features: No-Smoking: Rooms with 2-Double Beds and No-Smoking 1-King bed with pull-out sofa beds: Amenities include: Free, Reliable, Premium & Fast Wi-Fi, 24/7 Coffee & Lemon infused ice water, Breakfast Buffet (6:30 – 9:30 am), No Pets Allowed. In -Room Amenities include: 55-inch LG Flat Screen TV w/ HD channels, Refrigerator & Microwave Oven, Coffee Maker, Hair Dryer, Iron with Ironing board; work table & chair. Fresh, Hot Breakfast Buffet includes: Scramble Eggs, Bacon/Sausage, Hot Cereal, Cold Cereal, Various Breads, Various Pastries/Danishes/Muffins, Fresh Fruits & Yogurts; plus: Beverages: Coffees, Teas, Juices, Water, & Milk; and featuring make-your-own waffles. Additionally, we have a meeting room for a variety of events & meetings for maximum of 30 people.",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "will-omlor-will-omlor-eos-implementer",
    "businessId": "will-omlor-eos-implementer",
    "name": "Will Omlor",
    "title": "SBRA Member",
    "email": "will.omlor@eosworldwide.com",
    "phone": "610-425-2582",
    "bio": "Complete system with simple, practical tools to help business owners and leadership teams get more out of the business",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "grace-whitfield",
    "businessId": "vantage-insurance",
    "name": "Yamile Zabala",
    "title": "SBRA Member",
    "email": "zabalapy@diamondcu.com",
    "phone": "484-524-3147",
    "bio": "Join us at Diamond Credit Union – your partner in financial success. As a not-for-profit, member-owned institution, we prioritize your prosperity. From checking accounts that earn dividends to personalized solutions during any stage of your life – whether opening your first bank account or seeking business assistance – we’re here every step of your journey. Diamond is committed to your success, ensuring that whether it’s your personal or business milestones, you have a dedicated ally. Unlike commercial banks, our profits benefit you – the more we grow, the more you gain. Elevate your financial journey with Diamond, where membership means lasting wealth and success.",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "marisol-ortiz",
    "businessId": "reading-dermatology",
    "name": "Yomaira Polanco",
    "title": "SBRA Member",
    "email": "ypolanco@readingderm.com",
    "phone": "610-750-7891",
    "bio": "We provide skin care for the entire family, from infants to seniors as well as cosmetic skin care to \"gently soften the aging process\".",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "devin-brooks",
    "businessId": "sweet-laurel",
    "name": "Yvans Pochron",
    "title": "SBRA Member",
    "email": "yvans@b2bistro.com",
    "phone": "610-718-6105",
    "bio": "",
    "isOwner": false,
    "photo": ""
  },
  {
    "id": "zachary-bell-bell-media-group",
    "businessId": "bell-media-group",
    "name": "Zachary Bell",
    "title": "SBRA Member",
    "email": "Zach@Bellmediagrp.com",
    "phone": "610-207-7604",
    "bio": "Storytelling, Social Media Management, Content Creation, Design Services",
    "isOwner": false,
    "photo": "https://image-res-platform.s3.amazonaws.com/c49327f1%2Fforms%2Fattachments%2FLj7qhncHTfGX2uTGRQyo_Zack2020_%20001%20LinkedIn.jpg"
  }
] satisfies Member[];
